# Electronya GT Wheel Firmware Manifest
manifest:
  remotes:
    - name: electronya
      url-base: git@gitea.main-server.home:Electronya
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  self:
    path: app

  projects:
    - name: zephyr
      remote: zephyr
      repo-path: zephyr.git
      path: zephyr
      revision: v4.3-branch
      import: true
    - name: embedded-services
      remote: electronya
      repo-path: embedded-services.git
      path: apps/embedded-services
      revision: main
